#!/bin/zsh

REVERSE_ORDER=false
DRY_RUN=false

if [[ ${#} -gt 0 ]] && startsWithDash ${1}
then 
	[ ${1/-/} = 'n' -o ${1/-/} = '-new' ] && ecko -n " ${TURK} " && memsave -s && memread && shift
    ([[ ${1/-/} = 'd' ]] || [[ ${1/-/} = '-dry-run' ]]) && { ecko " \\U1f449\\U1f3fe Dry Run" 16 239; DRY_RUN=true; shift }
    ([[ ${1/-/} = 'r' ]] || [[ ${1/-/} = '-reverse' ]]) && { ecko " \\U1f449\\U1f3fd Reverse Order" 231 16; REVERSE_ORDER=true; shift }
fi

# cat  $TMP/brew-outdated.txt | (false && sort -r || sort)

_brew-upgrade-all () {
	CNT=1
	brew outdated --greedy ${1} | tee ${CSV_BREW_OUTDATED};
	for pkg in $(cat ${CSV_BREW_OUTDATED} | (${REVERSE_ORDER} && sort -r || sort))
	do
		ecko " \\U1f449\\U1f3fb ${1/--/} ${pkg}" 1 18 | tee -a "${CSV_BREW_PACKAGES_UPGRADING}"
		CURR_CMD="SUDO_ASKPASS=${BIN}/memecho breww upgrade --greedy ${1} ${pkg}"; # echo "${CURR_CMD}"
		${DRY_RUN} && { FG=$((${CNT}+16)); ecko ${CURR_CMD//${BIN}/\${BIN}} ${FG} $((248-${FG}));((CNT++)) } || eval "${CURR_CMD}"

	done
}
_brew-upgrade-all '--cask'
_brew-upgrade-all
