#!/bin/zsh

PREVIOUS_CSV=false
REVERSE_ORDER=false
DRY_RUN=false

POINT2RIGHT="\\U1f449\\U1f3fe \\U1f449\\U1f3fd \\U1f449\\U1f3fc \\U1f449\\U1f3fb"
POINT2LEFT="\\U1f448\\U1f3fb \\U1f448\\U1f3fc \\U1f448\\U1f3fd \\U1f448\\U1f3fe"

pointTo () {
	ecko " ${POINT2RIGHT} ${1} ${POINT2LEFT} " ${2:-1} ${3:-230}
}

if [[ ${#} -gt 0 ]] && startsWithDash ${1}
then 
    [ ${1/-/} = 'n' -o ${1/-/} = '-new' ]                               && pointTo "${TURK}" 255 160 && memsave -s && memread && shift
    [[ ${#} -gt 0 ]] && [ ${1/-/} = 'p' -o ${1/-/} = '-previous-csv' ]  && pointTo "Previous CSV" 232 118 && PREVIOUS_CSV=true && shift
    [[ ${#} -gt 0 ]] && [ ${1/-/} = 'r' -o ${1/-/} = '-reverse' ]       && pointTo "Reverse Order" 231 161 && REVERSE_ORDER=true && shift
    [[ ${#} -gt 0 ]] && [ ${1/-/} = 'd' -o ${1/-/} = '-dry-run' ]       && pointTo "Dry Run" 161 231 && DRY_RUN=true && shift
fi

# cat  $TMP/brew-outdated.txt | (false && sort -r || sort)

_brew-upgrade-all () {
	CNT=1
	${PREVIOUS_CSV} || brew outdated | tee ${CSV_BREW_OUTDATED}
	for pkg in $(cat ${CSV_BREW_OUTDATED} | (${REVERSE_ORDER} && sort -r || sort))
	do
		ecko " \\U1f449\\U1f3fb ${pkg}" 1 18 | tee -a "${1:-${CSV_BREW_PACKAGES_UPGRADING}}"
		CURR_CMD="SUDO_ASKPASS=${BIN}/memecho breww upgrade ${pkg}"
		${DRY_RUN} && { FG=$((${CNT}+16)); ecko ${CURR_CMD//${BIN}/\${BIN}} ${FG} $((248-${FG}));((CNT++)) } || eval "${CURR_CMD}"

	done
}
_brew-upgrade-all ${@}
