#!/bin/zsh

source ${HOME}/.debug_state

isDebug && echo "DEBUG ON"

if [[ -z "${OUTPUT_BREW}" ]]
then
    message-output "…sourcing…"
    source update-vars-output
fi

message-output "OUTPUT_BREW = ${OUTPUT_BREW}"
mkdir -p "${OUTPUT_BREW}"

TIMESTAMP="$(date +%s)"

BREW_FILE="${OUTPUT_BREW}/brew.${@}_${TIMESTAMP}.txt"
BREW_FILE="${BREW_FILE// /.}"

isDebug && echo "TIMESTAMP = ${TIMESTAMP}\nBREW_FILE = ${BREW_FILE}\nOUTPUT_BREW = ${OUTPUT_BREW}"

brew "${@}" --verbose --debug | tee "${BREW_FILE}"

NOTINSTALLED=$(cat "${BREW_FILE}" | grep -i 'not installed')
[[ -n ${NOTINSTALLED} ]] && echo "\t Not installed" || echo "\t already installed"
if [[ "${@}" == *"info"* ]] && [[ -n ${NOTINSTALLED} ]]
then
    CMD="${@}"
    echo -n "$(filename "${0}") ${CMD/info/install}" | pbcopy
fi
