#!/bin/zsh

ORGIFS="${IFS}"

IFS="${DELIMITER_ENDL}"

INPUT_STDIN=($(get-stdin &))

_capitalcase_ () {
	SZ_OUTPUT='' 
    SEP="${2:- }"
    SEP_LENGTH="${#2}"
    [[ ${SEP_LENGTH} -eq 0 ]] && ((SEP_LENGTH+=2)) || ((SEP_LENGTH++))
    IFS="${ORGIFS}"

    SZ_INPUT="$(echo "${1}" | sed -E 's/[^a-zA-Z]/ /g')"
    ARR_TMP=($(echo "${SZ_INPUT}")) 
	
    for w in ${ARR_TMP}
	do
		SZ_OUTPUT+="${w[1]:u}${w[2,-1]}${SEP}" 
	done
	echo ${SZ_OUTPUT[1,-${SEP_LENGTH}]}
}

if [[ -n ${INPUT_STDIN} ]]
then
    _capitalcase_ ${INPUT_STDIN} ${@}
else
    _capitalcase_  ${@}
fi
