#!/bin/zsh

IFS=${DELIMITER_ENDL}
INPUT_STDIN=($(get-stdin &))

    
BOLD='%b'
NL=$'\n'
KF='%k%f'
    
CNTR=0

_ecko() {

    #echo "$0 CNTR: ${CNTR} ; \$@ = $@; \$#= $#"
    if [[ "${1}" != "NO" ]]
    then
        for param in ${@}
        do
            if startsWithDash ${param}
            then
            
                ([[ ${param/-/} = "-bold" ]] || [[ ${param/-/} = "b" ]]) && BOLD='%B' && ((CNTR++)) && shift #&& echo bold
                ([[ ${param/-/} = "-newline" ]] || [[ ${param/-/} = "n" ]]) && NL='' && ((CNTR++)) & shift #&& echo newline
            fi
        done
    else
        shift
    fi
    
    TEXT="${1}" # && ((CNTR++)) #&& echo text
    shift


    FGC=''
    BGC=''

    [[ -n ${1} ]] && isNumeric ${1} && FGC="%F{${1}}"
    [[ -n ${2} ]] && isNumeric ${2} && BGC="%K{${2}}"
    [[ -n ${3} ]] && isNumeric ${3} && KF=''

    print -Pn "${FGC}${BGC}${BOLD}${TEXT}${KF}" ${NL} #  > /dev/stdin
}

if [[ -n ${INPUT_STDIN} ]]
then
    for line in ${INPUT_STDIN}
    do
        _ecko "NO" ${line} ${@}
    done
else
    _ecko ${@}
fi


