#!/bin/zsh

_isDebug () {
	#DEBUG=$(cat "${DEBUG_STATE_FILE}") 
	DEBUG=0
	if [[ ${DEBUG} -eq ${TRUE} ]] || [[ "${DEBUG}" = "${TRUE}" ]]
    then
        return 0
    else
        return 1
    fi
}
_isDebug ${@}
