#!/bin/zsh


_links-grep () {
	{
		case ${#} in
			(1) source isDebugLocal && echo "\$# = 1: \$1=$1"
				SZ_REGEX="${1}"  ;;
			(2) source isDebugLocal && echo "\$# = 2: \$1=$1, \$2 = $2"
				SZ_REGEX="${2}${1}${2}"  ;;
			(3) source isDebugLocal && echo "\$# = 3: \$1=$1, \$2=$2,  \$3=$3"
				SZ_REGEX="${2}${1}${3}"  ;;
		esac
		source isDebugLocal && echo "${SZ_REGEX}" && which -a grep
		grep ${GREP_EXCLUDE_DIR_NODE_MODULES} ${GREP_EXCLUDE_DIR_GIT} -ril . $LINKS | grep ${GREP_EXCLUDE_DIR_NODE_MODULES} ${GREP_EXCLUDE_DIR_GIT} -E "${SZ_REGEX}"
	} 2> /dev/null
}
_links-grep ${@}
