#!/bin/zsh

ISDEBUG=$(which isDebug | wc -l)

CNT_ALIASES=$(alias | wc -l)

isDebug && source ${SHELL_DEBUGSTATE}
[[ ${CNT_ALIASES} -lt 3  ]] && [[ -n ${SHELL_ALIASES} ]]  && [[ -r ${SHELL_ALIASES} ]] && source ${SHELL_ALIASES}
CNT_ALIASES=$(alias | wc -l)
[[ ${CNT_ALIASES} -lt 3  ]] && [[ -r ~/.shell_aliases ]] && source ~/.shell_aliases

INPUT="${1}"
IFS_ORIG=${IFS}
IFS=$','

if [ -n "${2}" ]; then
    IFS="${2}"
fi
#[[ -n "${3}" ]] && POST="${3}"
#[[ -n "${4}" ]] && PRE="${4}"

for i in $(echo ${INPUT}); do 
    echo "${4}${i}${3}"; 
done 

#resetIFS
IFS_PREV=(); IFS=${IFS_ORIG}
IFS=${IFS_ORIG}
