#!/bin/zsh

source $HOME/.debug_state

if isDebug; then 
    echo "Script $0"
    echo "CALLER $CALLER"
    echo "CALLERER $CALLERER"
fi

export ARR_PACKAGES=() 
export PACKAGES=($(npm -g outdated --depth=0 | list-col 1))

export TMP_CMDs=()
export TMP_PACKAGES=()

_populate_update_package_array () {

    for i in ${PACKAGES}
	do

		[[ "$i" != "Package" ]] && TMP_PACKAGES+="${i}"
        ecko "npm i -g ${i}@latest" 161 190
		[[ "$i" != "Package" ]] && npm i -g ${i}@latest
#		[[ "$i" != "Package" ]] && ARR_PACKAGES+=$i 
		[[ "$i" != "Package" ]] && ARR_PACKAGES+="npm i -g ${i}@latest"
        
        LAST_minus_1=$(($#ARR_PACKAGES-1))
        LAST=$#ARR_PACKAGES
    done
    list-array-elements ${ARR_PACKAGES}
}

_populate_update_package_array


