#!/bin/zsh

#echo "\$@ = ${@}"

RETURN_CODE="${1:-74}"

ecko " ➫ ${2} " 118 88 > /dev/stderr
#echo "\$RETURN_CODE = ${RETURN_CODE}"

[[ $SHLVL -gt 1 ]] && exit ${RETURN_CODE} || return ${RETURN_CODE}
