#!/bin/zsh

_terminal-check () {
	TMP_SCRIPT="${1:-${SHELL_VARS}}" 
    TMP_FILENAME=$(filename ${TMP_SCRIPT} | uppercase)
    ecko " Does \$${TMP_FILENAME:1} need to be sourced again? ${ARROWR[6]} " 190 161
    terminal-update-needed ${TMP_SCRIPT} && echo "${_TU1} YES" || echo "${_TD1} NO"
}
_terminal-check ${@}
