#!/bin/zsh

[[ ${#1} -eq 0 ]] && . retexit 9

_terminal-update-needed () {
    TERMSESSION_ID=${2:-${TERM_SESSION_ID}}

	CHECKSUM_OLD="$(shasum -a 512 "${1}")" 
    PATH_2_CHECKSUM_FILE="${CHECKSUMS_FOLDER}/${TERMSESSION_ID}•$(path2string "${1}")"
	
    CHECKSUM_CURRENT=''
    [[ -r "${PATH_2_CHECKSUM_FILE}" ]] && CHECKSUM_CURRENT="$(cat ${PATH_2_CHECKSUM_FILE})" 
	
    echo "\nCHECKSUM_OLD\t ${CHECKSUM_OLD}" >> "${TMPDIR}/debug-${TERMSESSION_ID}"
	echo "CHECKSUM_CURRENT\t ${CHECKSUM_CURRENT}" >> "${TMPDIR}/debug-${TERMSESSION_ID}"
	
    [[ "${CHECKSUM_OLD}" != "${CHECKSUM_CURRENT}" ]]
}
_terminal-update-needed ${@}
