#!/bin/zsh

source ${SHELL_VARS_OUTPUT}
IFS=${DELIMITER_ENDL}
CURR_FOLDER="${1}"
ARR_TREE=( $(which -a tree) )

_tree () {
	${ARR_TREE[-1]} "${1}" | tee ${OUTPUT_TREES}/tree_$(path2string "${1:-${PWD}}")_$(date +%s).txt
}
_tree "${CURR_FOLDER}"
